import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientQueryProvider from "./components/ClientQueryProvider";
import { Toaster } from "@/components/ui/sonner";

const uberFont = localFont({
  src: [
    {
      path: "./fonts/UberMoveTextLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/UberMoveTextRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/UberMoveTextMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/UberMoveTextBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-uber",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${uberFont.className} antialiased`}>
        <ClientQueryProvider>{children}</ClientQueryProvider>
        <Toaster closeButton position="top-right" richColors />
      </body>
    </html>
  );
}
